version: '3.9'
name: tp0
services:
  healthcheck:
    container_name: healthcheck
    image: alpine:edge
    networks:
    - testing_net
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /src/main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./server/config.ini:/config.ini
    networks:
    - testing_net
  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_DOCUMENT=95854312
    - CLI_NAME=Daniel Alejandro
    - CLI_LASTNAME=Lovera Lopez
    - CLI_BETNUMBER=7573
    - CLI_BIRTHDATE=1997-01-01
    - CLI_LOG_LEVEL=DEBUG
    - CLI_ID=1
    volumes:
    - ./client/config.yaml:/config.yaml
    networks:
    - testing_net
    depends_on:
    - server
  client_2:
    container_name: client_2
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_DOCUMENT=30904465
    - CLI_NAME=Santiago Lionel
    - CLI_LASTNAME=Lorca
    - CLI_BETNUMBER=7574
    - CLI_BIRTHDATE=1999-03-17
    - CLI_LOG_LEVEL=DEBUG
    - CLI_ID=2
    volumes:
    - ./client/config.yaml:/config.yaml
    networks:
    - testing_net
    depends_on:
    - server
  client_3:
    container_name: client_3
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_DOCUMENT=50219882
    - CLI_NAME=Ramon Andres
    - CLI_LASTNAME=Cardenas
    - CLI_BETNUMBER=7575
    - CLI_BIRTHDATE=2000-12-25
    - CLI_LOG_LEVEL=DEBUG
    - CLI_ID=3
    volumes:
    - ./client/config.yaml:/config.yaml
    networks:
    - testing_net
    depends_on:
    - server
  client_4:
    container_name: client_4
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_DOCUMENT=40118472
    - CLI_NAME=Carlos Esteban
    - CLI_LASTNAME=Poroto
    - CLI_BETNUMBER=7576
    - CLI_BIRTHDATE=1990-06-30
    - CLI_LOG_LEVEL=DEBUG
    - CLI_ID=4
    volumes:
    - ./client/config.yaml:/config.yaml
    networks:
    - testing_net
    depends_on:
    - server
  client_5:
    container_name: client_5
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_DOCUMENT=60129482
    - CLI_NAME=Francisco Javier
    - CLI_LASTNAME=Gonzalez
    - CLI_BETNUMBER=7577
    - CLI_BIRTHDATE=1995-09-15
    - CLI_LOG_LEVEL=DEBUG
    - CLI_ID=5
    volumes:
    - ./client/config.yaml:/config.yaml
    networks:
    - testing_net
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
