version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CLIENT_ID=1
    networks:
    - testing_net
    depends_on:
    - server
  client_2:
    container_name: client_2
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CLIENT_ID=2
    networks:
    - testing_net
    depends_on:
    - server
  client_3:
    container_name: client_3
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CLIENT_ID=3
    networks:
    - testing_net
    depends_on:
    - server
  client_4:
    container_name: client_4
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CLIENT_ID=4
    networks:
    - testing_net
    depends_on:
    - server
  client_5:
    container_name: client_5
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CLIENT_ID=5
    networks:
    - testing_net
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
